version: '3'

services:
  nginx:
    image: nginx
    container_name: nginx
    restart: always
    ports:
      - "443:443"
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ./certs/:/etc/nginx/ssl/
    depends_on:
      - docmost
      
  docmost:
    image: docmost/docmost:latest
    container_name: docmost
    depends_on:
      - db
      - redis
    environment:
      APP_URL: 'http://localhost'
      APP_SECRET: 'FAebayJNpkqzLmxg62YwdHjvC7TVD8'
      DATABASE_URL: 'postgresql://docmost:NtcTR5GBxJrjLgsAyUEzS4fP6evkZH@db:5432/docmost?schema=public'
      REDIS_URL: 'redis://redis:6379'
    ports:
      - "3000:3000"
    restart: unless-stopped
    volumes:
      - ./data/docmost_data:/app/data/storage

  db:
    image: postgres:16-alpine
    container_name: db
    environment:
      POSTGRES_DB: docmost
      POSTGRES_USER: docmost
      POSTGRES_PASSWORD: NtcTR5GBxJrjLgsAyUEzS4fP6evkZH
    restart: unless-stopped
    volumes:
      - ./data/db_data:/var/lib/postgresql/data

  redis:
    image: redis:7.2-alpine
    container_name: redis
    restart: unless-stopped
    volumes:
      - ./data/redis_data:/data


  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin4
    restart: always
    ports:
      - "8888:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin123
    volumes:
      - ./data/pgadmin:/var/lib/pgadmin

volumes:
  docmost:
  db_data:
  redis_data:
  
